### ISSUE TITLE
Tracks alot more honor than what i've actually gained

### ISSUE THREAD

**Issue by fix73** [mynian/LegionHonor#5]
When i enter a BG or an arena it tracks as i've gained alot more honor, than what i actually have. 1 Arena and it thinks i've earned like 20k honor.

This addon seems really cool and i love that u can set a honor goal. So is the issue on my end or is the tracker not working atm?

**Comment by mynian** [comment]
What exactly is calculating incorrectly?

**Comment by mynian** [comment]
Ok I ran a test arena match with a goal set and see what you are talking about. Going to dig into it.

**Comment by fix73** [comment]
Hope it's an easy fix hehe. I love the idea behind the addon btw ;)

**Comment by mynian** [comment]
it looks like it is. I originally created this addon back during Legion and I had called it "Legion Honor". When BfA dropped, I figured that the name should be something more appropriate to what it actually is.

Since I like to keep my code clean and easy to follow, I had named all my variables with the prefix "lh" originally, but had the bright idea to change all those prefixes to "ht" with the name change. It seems I missed one and you are the first person to notice since October 2020.

**Comment by mynian** [comment]
should be fixed in v3.1.3

**Comment by fix73** [comment]
Legion honor wouldn't really be the best name anymore i can that haha. I really like that you can set a goal and work towards it.

When will that version be availabe? v3.1.2 is on curse atm. But it says it has been updated today

**Comment by mynian** [comment]
Github decided to repush the .2 version instead of .3 for some reason. I forced a new release to curse and it should populate soon

**Comment by fix73** [comment]
Awesome man, can't wait to try it out then. Super cool that u were able to fix it so fast

**Comment by fix73** [comment]
Just downloaded the new version from wowinterface and it works perfectly now. Thank's for your work man
